### ISSUE TITLE
Hot fix some station/line names in English

### ISSUE THREAD

**Issue by trungvt-pnl** [adieuadieu/japan-train-data#2]
I tried to fix and push new branch into this repository but access is denied.
Many English names are not correct since they are translated directly from Google translate API.
I have fixed many ones but cannot do anything to contribute.
I think it is good enough to get the response from google search with the first result of Wikipedia in English, maybe.
Btw, thank you so much for this repository.

**Comment by adieuadieu** [comment]
Hi @trungvt-pnl — I'd happily accept a PR. If you're new to contributing to OSS projects, here are a few guides:
https://help.github.com/articles/fork-a-repo/
https://opensource.guide/how-to-contribute/#opening-a-pull-request
https://stackoverflow.com/a/4384824/845713

In short, simply fork this project, git clone and add your changes on your own fork, then come back here and raise (create) a new Pull Request. Looking forward to your contribution!
